### ISSUE TITLE
Incorrect discovery parameter on the chapter 3 yml file

### ISSUE THREAD

**Issue by Sh4dow-BR** [PacktPublishing/Threat-Hunting-with-Elastic-Stack#1]
Hey there!

While I was checking the github file on the yml file, I followed the format as follows:

```
# --------------------------------- Discovery ----------------------------------
#
# Pass an initial list of hosts to perform discovery when this node is started:
# The default list of hosts is ["127.0.0.1", "[::1]"]
#
discovery.node: single-node
discovery.seed_hosts: ["0.0.0.0"]
#
```

However, initially I was getting errors and didn't understand why.

When I checked the PDF/book version the single-node parameter is incorrect in the github file.

The correct is discovery.type and note discovery.node.. 
**_discovery.type: single-node_**

Thanks for the amazing book so far!

**Comment by peasead** [comment]
Ah, yeah. That looks right. Should be `discovery.type : single-node`.

Good eye and thanks for providing the solution.

https://www.elastic.co/guide/en/elasticsearch/reference/7.17/modules-discovery-settings.html#discovery.type
