### ISSUE TITLE
To make curl requests to Elastic 8.3 it's necessary to turn off xpack.security

### ISSUE THREAD

**Issue by Sh4dow-BR** [PacktPublishing/Threat-Hunting-with-Elastic-Stack#3]
Hello guys once again!

While trying to make curl requests to the initial Elasticsearch instance, I was getting the following error: curl: (52) Empty reply from server.

Elasticsearch was running as normal from systemctl status however the reply was empty.

Checking on stackoverflow, I saw the following post:
https://stackoverflow.com/questions/35921195/curl-52-empty-reply-from-server-timeout-when-querying-elastiscsearch

Which stated that we need to change xpack.security.enabled to false as it seems from Elastic 8.1, it's been a default setting.

```
#----------------------- BEGIN SECURITY AUTO CONFIGURATION -----------------------
#
# The following settings, TLS certificates, and keys have been automatically      
# generated to configure Elasticsearch security features on 13-08-2022 12:01:10
#
# --------------------------------------------------------------------------------

# Enable security features
xpack.security.enabled: true

```

So if we change xpack from true to false, we are now able to make curl requests without SSL.

`xpack.security.enabled: false`

### However, in the post it states that xpack needs to be true when Kibana is used!

Thanks once again!

**Comment by peasead** [comment]
Hey @Sh4dow-BR thanks for checking out the book and your comment. The book was written using version `7.x` as `8.x` hadn't been released yet.

With version `8.x` of the Elastic Stack, there were [tremendous architectural changes to its deployment, configuration, and management](https://www.elastic.co/blog/whats-new-elastic-8-0-0). One of those changes is the way that the Elastic Stack implements security. 

So, for a few suggestions that you can pursue depending on your use case:
1. Check out the Elastic documentation on a secure deployment of `8.x` [[Elasticsearch](https://www.elastic.co/guide/en/elasticsearch/reference/current/secure-cluster.html), [Kibana](https://www.elastic.co/guide/en/kibana/current/using-kibana-with-security.html)]
2. Check out [this project](https://github.com/peasead/elastic-container) that stands up a full and secure Elastic Stack using Docker with a single shell script (macOS or Linux)
